server:
  port: 8088
  servlet:
    context-path: /gestor

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/gestor_db
  mail:
    host: smtp.office365.com
    port: 587
    username: correonopersonal10@hotmail.com
    password: zhvvxvunucatafzn  # Contraseña de aplicacion generada en hotmail
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
        debug: true # Muestra logs detallados del envío

logging:
  level:
    org.springframework: INFO
