server:
  port: 8088
  servlet:
    context-path: /gestor

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/gestor_db
  mail:
    host: smtp.gmail.com
    port: 587
    username: correonopersonal10@gmail.com
    password: kbpv xbyc cjwl otpr
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
        debug: true # Útil para ver si Gmail acepta la conexión

logging:
  level:
    org.springframework: INFO