server:
  port: 8088
  servlet:
    context-path: /gestor

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/GestorProyectos
  mail:
    host: smtp.gmail.com
    port: 587
    username: jhoanvilla55@gmail.com
    password: zcjhtuslhrcpdmkg
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

# Logs y configuraci√≥n adicional
logging:
  level:
    org.springframework: INFO
