server:
  port: 8088
  servlet:
    context-path: /gestor

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/GestorProyectos

# Logs y configuraci√≥n adicional
logging:
  level:
    org.springframework: INFO
